steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', 'find /workspace -maxdepth 2'] # Lists files 2 deep in the build context
  id: 'List workspace contents'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/todolist-474507/todolist-repo/todolist:latest', '.']
  id: 'Build Docker Image'
images:
- 'europe-west1-docker.pkg.dev/todolist-474507/todolist-repo/todolist:latest'
options:
  logging: CLOUD_LOGGING_ONLY

# then execute this: gcloud builds submit --config cloudbuild.yaml .