steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', 'find /workspace -maxdepth 2'] # Lists files 2 deep in the build context
  id: 'List workspace contents'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/todolist-474507/todolist-repo/todo-list-app:$SHORT_SHA', '.']
  id: 'Build Docker Image'
  dir: 'week1_todo_list' # Set the working directory for the build

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/todolist-474507/todolist-repo/todo-list-app:$SHORT_SHA']
  id: 'Push Docker Image'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'todo-list-app'
  - '--image'
  - 'europe-west1-docker.pkg.dev/todolist-474507/todolist-repo/todo-list-app:$SHORT_SHA'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  id: 'Deploy to Cloud Run'

images:
- 'europe-west1-docker.pkg.dev/todolist-474507/todolist-repo/todo-list-app:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
