steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/apaplan-6a422/apaplan-repo/apaplan', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/apaplan-6a422/apaplan-repo/apaplan']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'auth'
  - '--image'
  - 'europe-west1-docker.pkg.dev/apaplan-6a422/apaplan-repo/apaplan'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-secrets=FIREBASE_WEB_API_KEY=FIREBASE_WEB_API_KEY:latest,SECRET_KEY=SECRET_KEY:latest,AUTH_DOMAIN=AUTH_DOMAIN:latest,PROJECT_ID=PROJECT_ID:latest,STORAGE_BUCKET=STORAGE_BUCKET:latest,MESSAGING_SENDER_ID=MESSAGING_SENDER_ID:latest,APP_ID=APP_ID:latest,MEASUREMENT_ID=MEASUREMENT_ID:latest'
images:
- 'europe-west1-docker.pkg.dev/apaplan-6a422/apaplan-repo/apaplan'
